version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Build redash docker image
        command: |
          cd redash
          docker build .
      - run:
        name: List docker images
        command: docker image list
