version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6-alpine
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: u1
          POSTGRES_DB: d1
          POSTGRES_PASSWORD: ""
        name: p1
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: u2
          POSTGRES_DB: d2
          POSTGRES_PASSWORD: ""
        name: p2
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            psql postgres://u1@p1/d1 -c "CREATE TABLE t1(i int)"
            psql postgres://u1@p1/d1 -c "SELECT * FROM t1"
            psql postgres://u2@p2/d2 -c "CREATE TABLE t2(i int)"
            psql postgres://u2@p2/d2 -c "SELECT * FROM t2"
