version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6-alpine
      - image: circleci/postgres:9.6-alpine
        name: "varanusdb"
        environment:
          POSTGRES_USER: "varanus"
          POSTGRES_DB: "varanus-test"
          POSTGRES_PASSWORD: ""
      - image: circleci/postgres:9.6-alpine
        name: "redashdb"
        environment:
          POSTGRES_USER: "redash"
          POSTGRES_DB: "redash"
          POSTGRES_PASSWORD: ""
      - image: redis:3.0-alpine
        name: "redashredis"
    steps:
      - run:
          name: Test PostgreSQL
          command: |
            sleep 10
            psql postgres://varanus@varanusdb/varanus-test -c "CREATE TABLE t1(i int)"
            psql postgres://varanus@varanusdb/varanus-test -c "SELECT * FROM t1"
            psql postgres://redash@redashdb/redash -c "CREATE TABLE t2(i int)"
            psql postgres://redash@redashdb/redash -c "SELECT * FROM t2"
