version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: p1
          POSTGRES_DB: p1
          POSTGRES_PASSWORD: ""
        name: p1
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: p2
          POSTGRES_DB: p2
          POSTGRES_PASSWORD: ""
        name: p2
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            psql postgres://vagrant@p1/vagrant-test -c "CREATE TABLE p1(i int)"
            psql postgres://vagrant@p1/vagrant-test -c "SELECT * FROM p1"
            psql postgres://vagrant@p2/vagrant-test -c "CREATE TABLE p2(i int)"
            psql postgres://vagrant@p2/vagrant-test -c "SELECT * FROM p2"
