version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: p1
          POSTGRES_DB: p1
          POSTGRES_PASSWORD: ""
        name: p1
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: p2
          POSTGRES_DB: p2
          POSTGRES_PASSWORD: ""
        name: p2
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            ls
